seed_search_queries:
  - "the local train songs"
  - "the local train albums"
  - "kappa tv music mojo"
  - "coke studio bharat best songs"
  - "anuv jain songs"
  - "anuv jain albums"
  - "vidya vox songs"
  - "vidya vox albums"
  - "prateek kuhad songs"
  - "prateek kuhad albums"
  - "papon unplugged"
  - "mtv unplugged india"
  - "t series mixtape"
  - "sony music india"
  - "old hindi songs"
  - "sufi songs"
  - "kishore kumar songs"
  - "indipop songs 90s"
  - "hindi music"
  - "hindi bollywood songs"
  - "punjabi songs"
  - "artist:sajjad ali"
  - "channel: nescafe basement"
  - "playlist: coke studio pakistan"
  - "album: coke studio"
  - "sufi songs"
  - "ghazals"
  - "artist:mustafa zahid"
  - "emraan hashmi songs"
  - "artist:atif aslam"
  - "artist:rahat fateh ali khan"
  - "T-Series"
  - "sony music india"
  - "tips official"
  - "yrf"
  - "zeemusiccompany"
  - "hindi bollywood songs"
  - "punjabi songs"
  - "malayalam songs"
  - "bengali songs"
  - "marathi songs"
  - "gujarati songs"
  - "haryanvi songs"
  - "odia songs"
  - "bhojpuri songs"
  - "assamese songs"
  - "rajasthani songs"
  - "urdu songs"
  - "english songs"
  - "hindi songs"
  - "tamil songs"
  - "telugu songs"
  - "kannada songs"
search_depth: 50
debug_level: "info"
