seed_search_queries:
  - "artist:sajjad ali"
  - "channel: nescafe basement"
  - "playlist: coke studio pakistan"
  - "album: coke studio"
  - "sufi songs"
  - "ghazals"
  - "artist:mustafa zahid"
  - "emraan hashmi songs"
  - "artist:atif aslam"
  - "artist:rahat fateh ali khan"
  - "T-Series"
  - "sony music india"
  - "tips official"
  - "yrf"
  - "zeemusiccompany"
  - "hindi bollywood songs"
  - "punjabi songs"
  - "malayalam songs"
  - "bengali songs"
  - "marathi songs"
  - "gujarati songs"
  - "haryanvi songs"
  - "odia songs"
  - "bhojpuri songs"
  - "assamese songs"
  - "rajasthani songs"
  - "urdu songs"
  - "english songs"
  - "hindi songs"
  - "tamil songs"
  - "telugu songs"
  - "kannada songs"
search_depth: 25
debug_level: "debug"
