seed_search_queries:
  - "the local train songs"
  - "the local train albums"
  - "kappa tv music mojo"
  - "coke studio bharat best songs"
  - "anuv jain songs"
  - "anuv jain albums"
  - "vidya vox songs"
  - "vidya vox albums"
  - "prateek kuhad songs"
  - "prateek kuhad albums"
  - "papon unplugged"
  - "mtv unplugged india"
  - "t series mixtape"
search_depth: 50
debug_level: "debug"
